In [7]:
import numpy as np
import pandas as pd
from  sklearn.preprocessing import StandardScaler
from  sklearn.model_selection import train_test_split
from sklearn import  svm
from sklearn.metrics import accuracy_score


In [8]:
data=pd.read_csv('diabetes.csv')

In [9]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [14]:
data=data[['Glucose','BloodPressure','Insulin','BMI','DiabetesPedigreeFunction','Age','Outcome']]

In [15]:
data.head()#189,60,23,846,30.1,0.398,59

Glucose  BloodPressure  Insulin   BMI  DiabetesPedigreeFunction  Age  \
0      148             72        0  33.6                     0.627   50   
1       85             66        0  26.6                     0.351   31   
2      183             64        0  23.3                     0.672   32   
3       89             66       94  28.1                     0.167   21   
4      137             40      168  43.1                     2.288   33   

   Outcome  
0        1  
1        0  
2        1  
3        0  
4        1

In [19]:
data.describe()

Glucose  BloodPressure     Insulin         BMI  \
count  768.000000     768.000000  768.000000  768.000000   
mean   120.894531      69.105469   79.799479   31.992578   
std     31.972618      19.355807  115.244002    7.884160   
min      0.000000       0.000000    0.000000    0.000000   
25%     99.000000      62.000000    0.000000   27.300000   
50%    117.000000      72.000000   30.500000   32.000000   
75%    140.250000      80.000000  127.250000   36.600000   
max    199.000000     122.000000  846.000000   67.100000   

       DiabetesPedigreeFunction         Age     Outcome  
count                768.000000  768.000000  768.000000  
mean                   0.471876   33.240885    0.348958  
std                    0.331329   11.760232    0.476951  
min                    0.078000   21.000000    0.000000  
25%                    0.243750   24.000000    0.000000  
50%                    0.372500   29.000000    0.000000  
75%                    0.626250   41.000000    1.000000  
max                    2.420000   81.000000    1.000000

In [ ]:
 data['Outcome'].value_counts()

In [23]:
data.groupby('Outcome').mean()

Glucose  BloodPressure     Insulin        BMI  \
Outcome                                                     
0        109.980000      68.184000   68.792000  30.304200   
1        141.257463      70.824627  100.335821  35.142537   

         DiabetesPedigreeFunction        Age  
Outcome                                       
0                        0.429734  31.190000  
1                        0.550500  37.067164

In [27]:
x=data.drop(columns='Outcome')
y=data['Outcome']

In [28]:
scaler=StandardScaler()

In [30]:
scaler.fit(x)

StandardScaler()

In [32]:
standardized_data=scaler.transform(x)

In [33]:
print(standardized_data)

[[ 0.84832379  0.14964075 -0.69289057  0.20401277  0.46849198  1.4259954 ]
 [-1.12339636 -0.16054575 -0.69289057 -0.68442195 -0.36506078 -0.19067191]
 [ 1.94372388 -0.26394125 -0.69289057 -1.10325546  0.60439732 -0.10558415]
 ...
 [ 0.00330087  0.14964075  0.27959377 -0.73518964 -0.68519336 -0.27575966]
 [ 0.1597866  -0.47073225 -0.69289057 -0.24020459 -0.37110101  1.17073215]
 [-0.8730192   0.04624525 -0.69289057 -0.20212881 -0.47378505 -0.87137393]]


In [34]:
x=standardized_data

In [36]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2,stratify=y)

In [37]:
classifier=svm.SVC(kernel='linear')

In [38]:
classifier.fit(X_train,y_train)

SVC(kernel='linear')

In [39]:
y_pred=classifier.predict(X_train)

In [40]:
training_accuracy= accuracy_score(y_pred,y_train)

In [41]:
training_accuracy

0.7850162866449512

In [42]:
y_pred_test=classifier.predict(X_test)
training_accuracy_test= accuracy_score(y_pred_test,y_test)

In [43]:
training_accuracy_test

0.7662337662337663

In [71]:
input_data =(115,0,0,35.3,0.134,29)


In [72]:
input_data_as_numpy_array =np.asarray(input_data)

In [73]:
input_data_reshape=input_data_as_numpy_array.reshape(1,-1)

In [74]:
std_data=scaler.transform(input_data_reshape)

C:\Users\shubh\anaconda3\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [75]:
prediction=classifier.predict(std_data)

In [76]:
print(prediction)

[0]
